#!/usr/bin/env bash

set -e

action=$1
exit_status=$2
shift 2

case "$action" in
    *)
        echo "Post-hook for action '$action'"
        echo -e "\tlink hooks directory in SVN ROOT"
        /bin/ln -sf ${SVN_WRAPPER}/samples/hooks $HOOK_DIR
        exit 0
    ;;
esac

exit 1
